# Generated by Django 5.1.1 on 2024-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demofiles',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='demofiles'),
        ),
        migrations.AlterField(
            model_name='demofiles',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='demofiles'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
